[package]
name = "sfshr"
version = "0.1.0"
authors = ["ondralukes <mail@ondralukes.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
openssl = "0.10.30"
base64 = "0.12.3"
simpletcp = "0.5.0"