[package]
name = "sfshr-server"
version = "0.1.0"
authors = ["ondralukes <mail@ondralukes.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simpletcp = "0.3.1"
rand = "0.7.3"
hex = "0.4.2"